### ISSUE TITLE
./make-all.sh --target=es2k  failed on Rocky 9.1

### ISSUE THREAD

**Issue by jiriproX** [ipdk-io/networking-recipe#270]
I'm trying to deploy IPDK Networking Recipe on Host with Rocky 9.1 The host has IPU card installed with MEV-TS images.
I'm deploying it according https://github.com/ipdk-io/networking-recipe/blob/main/docs/guides/setup/es2k-setup-guide.md  and have a build issue during ./make-all.sh --target=es2k   step.
Have you seen such error?

STDERR:

configure.ac:25: installing 'build-aux/compile'
configure.ac:40: installing 'build-aux/config.guess'
configure.ac:40: installing 'build-aux/config.sub'
configure.ac:23: installing 'build-aux/install-sh'
configure.ac:23: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
configure: WARNING: you should use --build, --host, --target
configure: WARNING: you should use --build, --host, --target
configure: WARNING: you should use --build, --host, --target
configure: WARNING: you should use --build, --host, --target
configure: WARNING: cannot find libcap-ng.
--user option will not be supported on Linux.
(you may use --disable-libcapng to suppress this warning).
gmake[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Building ES2K_TARGET
CMake Error at cmake/es2k-driver.cmake:16 (find_library):
  Could not find LIBBF_SWITCHD using the following names: bf_switchd_lib
Call Stack (most recent call first):
  cmake/es2k-driver.cmake:149 (_define_es2k_driver)
  CMakeLists.txt:171 (include)

**Comment by ffoulkes** [comment]
1. Are you building the IPDK Networking Recipe for an x86 host, or are you cross-compiling for the ACC? If it's the latter, the most recent documentation is in the [Building P4 Control Plane for the ACC](https://ipdk.io/p4cp-userguide/guides/es2k/building-acc-p4cp.html) section of the [P4 Control Plane User Guide](https://ipdk.io/p4cp-userguide/index.html).
> The actual location of the helper scripts depends on which version of Networking Recipe. They're in the base directory in older releases, and in `scripts/es2k` in newer versions.
2. From the symptoms you describe, my guess is that the build script doesn't have the correct location for the SDE installation. It normally gets these from the `SDE_INSTALL` environment variable or the `--sde` option of the helper script.
3. [PR #269](https://github.com/ipdk-io/networking-recipe/pull/269) adds [documentation for make-all.sh](https://github.com/ipdk-io/networking-recipe/blob/eb8f28ae29e5a6aaf0428567406ed2dcc2929208/docs/scripts/make-all.rst). (Caution: This is a first draft, and hasn't been reviewed yet.) It's also for a newer version of `make-all.sh` (some of which is in another PR), but most of the information should be correct. Do a `./make-all.sh -h` to see which of the options your version of make-all supports.

**Comment by ffoulkes** [comment]
No response from OP, and there have been no further reports of this issue.

Closing issue on the assumption that the suggested remedy (defining `SDE_INSTALL`, as the user guide recommends) solved the problem.
